// Code generated by goctl. DO NOT EDIT.
package types

type CreateCommentReq struct {
	ArticleId int64  `json:"articleId"`
	Comment   string `json:"comment"`
}

type DeleteCommentReq struct {
	ArticleId int64 `json:"articleId"`
	CommentId int64 `json:"commentId"`
}

type UpdateCommentReq struct {
	ArticleId int64  `json:"articleId"`
	CommentId int64  `json:"commentId"`
	Comment   string `json:"comment"`
}

type GetAllCommentReq struct {
	ArticleId     int64  `json:"articleId"`
	Method        string `json:"method,options=[time,score],default=score"`
	LastCommentId int64  `json:"lastCommentId,default=0"`
	PageNumber    int64  `json:"pageNumber,default=10"`
}

type PostCommentLikeReq struct {
	ArticleId int64 `json:"articleId"`
	CommentId int64 `json:"commentId"`
}

type CommentToCommentReq struct {
	ArticleId  int64  `json:"articleId"`
	CommmentId int64  `json:"commentId"`
	Comment    string `json:"comment"`
}

type UpdateCommenttocReq struct {
	FirstCommentId int64  `json:"firstCommentId"`
	CommentId      int64  `json:"commentId"`
	Comment        string `json:"comment"`
}

type DeleteCommenttocReq struct {
	FirstCommentId int64 `json:"firstCommentId"`
	CommentId      int64 `json:"commentId"`
}

type GetCommenttocReq struct {
	FirstCommentId int64  `json:"firstCommentId"`
	Method         string `json:"method,options=[time,score],default=score"`
	LastCommentId  int64  `json:"lastCommentId,default=0"`
	PageNumber     int64  `json:"pageNumber,default=10"`
}

type PostCommenttocLikeReq struct {
	FirstCommentId int64 `json:"firstCommentId"`
	CommentId      int64 `json:"commentId"`
}

type GetCommentCountReq struct {
	RequireId int64 `json:"requireId"`
}

type HttpCode struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
